
INSERT INTO stories (user_id, title, content, published_status, date_created) VALUES (1, 'Nikita, the Sled Dog', 'The morning air was crisp and cold, and the only sounds that could be heard were the soft padding of dog paws on snow and the jingle of harnesses. Nikita was at the front of the sled, her thick fur coat glistening in the early light. She was a purebred Alaskan Husky, born to run and bred for the harsh conditions of the north. Her piercing blue eyes scanned the landscape ahead, alert for any signs of danger. Nikitas human companion, a grizzled man named Jack, sat behind her, his weathered face set in a determined expression. Jack had been a sled dog racer for over a decade, and he knew the Alaskan wilderness like the back of his hand. He trusted Nikita and the other dogs on his team implicitly, knowing that they would guide him through the treacherous terrain and protect him from the wild animals that roamed the area.', 'false', DEFAULT);

INSERT INTO stories (user_id, title, content, published_status, date_created) VALUES (2, 'Bella, the Drug-Sniffing Dog', 'Bella was a highly trained drug-sniffing dog, with a keen sense of smell and an unbreakable spirit. She and her handler, Officer Gomez, had been partners for two years, and together they had been responsible for countless drug busts and arrests. Bella was proud of her work and loved the thrill of the chase. One day, Bella and Officer Gomez received a tip about a drug cartel operating in a small town just outside of the city. They were told that the cartel was smuggling large amounts of drugs into the city, and that they had a well-organized system in place to avoid detection. Officer Gomez knew that this would be a difficult case, but he also knew that Bella was up for the challenge. As they arrived in the town, Bella immediately went to work. She sniffed around buildings and cars, using her nose to detect even the smallest traces of illegal substances. Officer Gomez watched her closely, admiring her dedication and skill. Bella was relentless, and she refused to give up until she had found what she was looking for..', 'false', DEFAULT);


INSERT INTO stories (user_id, title, content, published_status, date_created) VALUES (3, 'Max, the Therapy Dog' ,'Max was a golden retriever with a gentle soul and a heart full of love. He was a certified therapy dog, trained to provide comfort and support to people in need. Max and his owner, Emily, spent their days visiting hospitals, nursing homes, and schools, bringing smiles to the faces of everyone they met. One day, Max and Emily received a special request. They were asked to visit a childrens hospital to meet with a young boy named Ben. Ben had been in the hospital for several weeks, undergoing treatment for a serious illness. He was feeling sad and scared, and his parents were desperate to find something that would cheer him up. Max and Emily arrived at the hospital, and they were escorted to Bens room. When they entered, they saw a small boy with a pale face and tired eyes, lying in bed with a stack of books beside him. Emily introduced Max, and the dog immediately jumped onto the bed, snuggling up to Ben and wagging his tail. At first, Ben was hesitant. He had never met a therapy dog before, and he was not sure what to expect. But as Max nuzzled him and licked his face, Ben began to relax. He reached out and petted Maxs soft fur, feeling a sense of comfort and happiness that he had not felt in weeks.', 'true', DEFAULT);

INSERT INTO stories (user_id, title, content, published_status, date_created) VALUES (3, 'Rocky, the Rescue Dog', 'Rocky was a big, burly German Shepherd with a heart of gold. He had been trained as a search and rescue dog, and he had saved countless lives over the years. Rockys handler, Sarah, was proud of him and knew that he was one of the best rescue dogs in the country. One day, Sarah and Rocky received a distress call. A hiker was lost in the wilderness, and he was running out of food and water. The weather was getting colder, and there was a chance that he might not survive the night. Sarah knew that they had to act fast. She and Rocky arrived at the trailhead and began their search. Rocky sniffed around, his nose twitching as he searched for the hikers scent. Sarah followed him closely, calling out the hikers name and hoping for a response. As they walked deeper into the woods, the terrain became more rugged and the air grew colder. Rockys fur stood on end, and Sarah knew that they were getting close. Suddenly, she heard a faint cry for help in the distance.', 'false', DEFAULT);
